#! /bin/bash

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep active | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export f"$num"="$num"
  export fnum=f"$num"
done

workspaces() {
  if [[ ${1:0:9} == "workspace" ]]; then #set focused workspace
    unset -v "$fnum"
    num=${1:11}
    export f"$num"="$num"
    export fnum=f"$num"

  elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
    num=${1:17}
    export o"$num"="$num"
    export f"$num"="$num"

  elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
    num=${1:18}
    unset -v o"$num" f"$num"
  fi

  #output eww widget
  echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
            (box	:class \"works\" :orientation \"h\" :spacing 5 :space-evenly \"true\" 	\
                (button :onclick \"hyprctl dispatch workspace 1\" :class \"i$o1$f1 btn\" (workspcbtn)) \
                (button :onclick \"hyprctl dispatch workspace 2\" :class \"i$o2$f2 btn\" (workspcbtn)) \
                (button :onclick \"hyprctl dispatch workspace 3\" :class \"i$o3$f3 btn\" (workspcbtn)) \
                (button :onclick \"hyprctl dispatch workspace 4\" :class \"i$o4$f4 btn\" (workspcbtn)) \
                (button :onclick \"hyprctl dispatch workspace 5\" :class \"i$o5$f5 btn\" (workspcbtn)) \
                (button :onclick \"hyprctl dispatch workspace 6\" :class \"i$o6$f6 btn\" (workspcbtn)) \
                (button :onclick \"hyprctl dispatch workspace 7\" :class \"i$o7$f7 btn\" (workspcbtn)) \
            )\
          )"
}

workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
  workspaces "$event"
done
